Algoritmo "Correção - Calculadora"

Var

base, altura, area : real

Inicio

// ENTRADA
// receber area e altura
escreval ("Qual é a base do retangulo?")
leia (base)
limpatela()

escreval ("Qual é a altura do retangulo?")
leia (altura)
limpatela()

// PROCESSAMENTO
// calcular a area
area <- base*altura

// SAIDA
// retornar a area calculada
escreval("A area do retangulo é: ", area)
escreval("        ")
escreval("Prontinho! ")

Fimalgoritmo