Algoritmo "repetições"

Var
contador : inteiro
contador2 : inteiro
contador3 : inteiro

Inicio
// while
enquanto (contador <= 10) faca
         escreval (contador)
         contador <- contador + 1

fimenquanto


//for
escreval ("PARA (FOR)")
         para contador2 <- 1 ate 10 passo 1 faca

          fimpara
// UNTIL
escreval ("REPITA (UNTIL)")
repita
      escreval(contador3)
      contador3 <- contador3 + 1

ate (contador3 = 11)

Fimalgoritmo