Algoritmo "Tabuada do 8"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/10/2024
Var

resultado, x : inteiro

Inicio

           escreval("          TABUADA DO 8          ")

para x <- 1 ate 10 passo 1 faca
     resultado <- 8 * x
     escreval("8 x", x, " = ", resultado)

fimpara

fimalgoritmo